# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BlendFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BlendFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBlendFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BlendFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BlendFrame
    def FrameIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BlendFrame
    def Tween(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # BlendFrame
    def BlendFunc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.BlendFunc import BlendFunc
            obj = BlendFunc()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BlendFrame
    def EasingData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.EasingData import EasingData
            obj = EasingData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(4)
def BlendFrameStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddFrameIndex(builder, frameIndex): builder.PrependInt32Slot(0, frameIndex, 0)
def BlendFrameAddFrameIndex(builder, frameIndex):
    """This method is deprecated. Please switch to AddFrameIndex."""
    return AddFrameIndex(builder, frameIndex)
def AddTween(builder, tween): builder.PrependBoolSlot(1, tween, 1)
def BlendFrameAddTween(builder, tween):
    """This method is deprecated. Please switch to AddTween."""
    return AddTween(builder, tween)
def AddBlendFunc(builder, blendFunc): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(blendFunc), 0)
def BlendFrameAddBlendFunc(builder, blendFunc):
    """This method is deprecated. Please switch to AddBlendFunc."""
    return AddBlendFunc(builder, blendFunc)
def AddEasingData(builder, easingData): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(easingData), 0)
def BlendFrameAddEasingData(builder, easingData):
    """This method is deprecated. Please switch to AddEasingData."""
    return AddEasingData(builder, easingData)
def End(builder): return builder.EndObject()
def BlendFrameEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)