# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CheckBoxOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CheckBoxOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCheckBoxOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CheckBoxOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CheckBoxOptions
    def WidgetOptions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.WidgetOptions import WidgetOptions
            obj = WidgetOptions()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CheckBoxOptions
    def BackGroundBoxData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CheckBoxOptions
    def BackGroundBoxSelectedData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CheckBoxOptions
    def FrontCrossData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CheckBoxOptions
    def BackGroundBoxDisabledData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CheckBoxOptions
    def FrontCrossDisabledData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CheckBoxOptions
    def SelectedState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # CheckBoxOptions
    def Displaystate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def Start(builder): builder.StartObject(8)
def CheckBoxOptionsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddWidgetOptions(builder, widgetOptions): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(widgetOptions), 0)
def CheckBoxOptionsAddWidgetOptions(builder, widgetOptions):
    """This method is deprecated. Please switch to AddWidgetOptions."""
    return AddWidgetOptions(builder, widgetOptions)
def AddBackGroundBoxData(builder, backGroundBoxData): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(backGroundBoxData), 0)
def CheckBoxOptionsAddBackGroundBoxData(builder, backGroundBoxData):
    """This method is deprecated. Please switch to AddBackGroundBoxData."""
    return AddBackGroundBoxData(builder, backGroundBoxData)
def AddBackGroundBoxSelectedData(builder, backGroundBoxSelectedData): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(backGroundBoxSelectedData), 0)
def CheckBoxOptionsAddBackGroundBoxSelectedData(builder, backGroundBoxSelectedData):
    """This method is deprecated. Please switch to AddBackGroundBoxSelectedData."""
    return AddBackGroundBoxSelectedData(builder, backGroundBoxSelectedData)
def AddFrontCrossData(builder, frontCrossData): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(frontCrossData), 0)
def CheckBoxOptionsAddFrontCrossData(builder, frontCrossData):
    """This method is deprecated. Please switch to AddFrontCrossData."""
    return AddFrontCrossData(builder, frontCrossData)
def AddBackGroundBoxDisabledData(builder, backGroundBoxDisabledData): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(backGroundBoxDisabledData), 0)
def CheckBoxOptionsAddBackGroundBoxDisabledData(builder, backGroundBoxDisabledData):
    """This method is deprecated. Please switch to AddBackGroundBoxDisabledData."""
    return AddBackGroundBoxDisabledData(builder, backGroundBoxDisabledData)
def AddFrontCrossDisabledData(builder, frontCrossDisabledData): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(frontCrossDisabledData), 0)
def CheckBoxOptionsAddFrontCrossDisabledData(builder, frontCrossDisabledData):
    """This method is deprecated. Please switch to AddFrontCrossDisabledData."""
    return AddFrontCrossDisabledData(builder, frontCrossDisabledData)
def AddSelectedState(builder, selectedState): builder.PrependBoolSlot(6, selectedState, 1)
def CheckBoxOptionsAddSelectedState(builder, selectedState):
    """This method is deprecated. Please switch to AddSelectedState."""
    return AddSelectedState(builder, selectedState)
def AddDisplaystate(builder, displaystate): builder.PrependBoolSlot(7, displaystate, 1)
def CheckBoxOptionsAddDisplaystate(builder, displaystate):
    """This method is deprecated. Please switch to AddDisplaystate."""
    return AddDisplaystate(builder, displaystate)
def End(builder): return builder.EndObject()
def CheckBoxOptionsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)