# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ColorFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ColorFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsColorFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ColorFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ColorFrame
    def FrameIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ColorFrame
    def Tween(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # ColorFrame
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ColorFrame
    def EasingData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.EasingData import EasingData
            obj = EasingData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(4)
def ColorFrameStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddFrameIndex(builder, frameIndex): builder.PrependInt32Slot(0, frameIndex, 0)
def ColorFrameAddFrameIndex(builder, frameIndex):
    """This method is deprecated. Please switch to AddFrameIndex."""
    return AddFrameIndex(builder, frameIndex)
def AddTween(builder, tween): builder.PrependBoolSlot(1, tween, 1)
def ColorFrameAddTween(builder, tween):
    """This method is deprecated. Please switch to AddTween."""
    return AddTween(builder, tween)
def AddColor(builder, color): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(color), 0)
def ColorFrameAddColor(builder, color):
    """This method is deprecated. Please switch to AddColor."""
    return AddColor(builder, color)
def AddEasingData(builder, easingData): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(easingData), 0)
def ColorFrameAddEasingData(builder, easingData):
    """This method is deprecated. Please switch to AddEasingData."""
    return AddEasingData(builder, easingData)
def End(builder): return builder.EndObject()
def ColorFrameEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)