# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Frame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Frame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Frame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Frame
    def PointFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.PointFrame import PointFrame
            obj = PointFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def ScaleFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ScaleFrame import ScaleFrame
            obj = ScaleFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def ColorFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ColorFrame import ColorFrame
            obj = ColorFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def TextureFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.TextureFrame import TextureFrame
            obj = TextureFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def EventFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.EventFrame import EventFrame
            obj = EventFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def IntFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.IntFrame import IntFrame
            obj = IntFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def BoolFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.BoolFrame import BoolFrame
            obj = BoolFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def InnerActionFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.InnerActionFrame import InnerActionFrame
            obj = InnerActionFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Frame
    def BlendFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.BlendFrame import BlendFrame
            obj = BlendFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(9)
def FrameStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddPointFrame(builder, pointFrame): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pointFrame), 0)
def FrameAddPointFrame(builder, pointFrame):
    """This method is deprecated. Please switch to AddPointFrame."""
    return AddPointFrame(builder, pointFrame)
def AddScaleFrame(builder, scaleFrame): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(scaleFrame), 0)
def FrameAddScaleFrame(builder, scaleFrame):
    """This method is deprecated. Please switch to AddScaleFrame."""
    return AddScaleFrame(builder, scaleFrame)
def AddColorFrame(builder, colorFrame): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(colorFrame), 0)
def FrameAddColorFrame(builder, colorFrame):
    """This method is deprecated. Please switch to AddColorFrame."""
    return AddColorFrame(builder, colorFrame)
def AddTextureFrame(builder, textureFrame): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(textureFrame), 0)
def FrameAddTextureFrame(builder, textureFrame):
    """This method is deprecated. Please switch to AddTextureFrame."""
    return AddTextureFrame(builder, textureFrame)
def AddEventFrame(builder, eventFrame): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(eventFrame), 0)
def FrameAddEventFrame(builder, eventFrame):
    """This method is deprecated. Please switch to AddEventFrame."""
    return AddEventFrame(builder, eventFrame)
def AddIntFrame(builder, intFrame): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(intFrame), 0)
def FrameAddIntFrame(builder, intFrame):
    """This method is deprecated. Please switch to AddIntFrame."""
    return AddIntFrame(builder, intFrame)
def AddBoolFrame(builder, boolFrame): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(boolFrame), 0)
def FrameAddBoolFrame(builder, boolFrame):
    """This method is deprecated. Please switch to AddBoolFrame."""
    return AddBoolFrame(builder, boolFrame)
def AddInnerActionFrame(builder, innerActionFrame): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(innerActionFrame), 0)
def FrameAddInnerActionFrame(builder, innerActionFrame):
    """This method is deprecated. Please switch to AddInnerActionFrame."""
    return AddInnerActionFrame(builder, innerActionFrame)
def AddBlendFrame(builder, blendFrame): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(blendFrame), 0)
def FrameAddBlendFrame(builder, blendFrame):
    """This method is deprecated. Please switch to AddBlendFrame."""
    return AddBlendFrame(builder, blendFrame)
def End(builder): return builder.EndObject()
def FrameEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)