# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ImageViewOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImageViewOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImageViewOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImageViewOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImageViewOptions
    def WidgetOptions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.WidgetOptions import WidgetOptions
            obj = WidgetOptions()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImageViewOptions
    def FileNameData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImageViewOptions
    def CapInsets(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.CapInsets import CapInsets
            obj = CapInsets()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImageViewOptions
    def Scale9Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.FlatSize import FlatSize
            obj = FlatSize()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImageViewOptions
    def Scale9Enabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def Start(builder): builder.StartObject(5)
def ImageViewOptionsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddWidgetOptions(builder, widgetOptions): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(widgetOptions), 0)
def ImageViewOptionsAddWidgetOptions(builder, widgetOptions):
    """This method is deprecated. Please switch to AddWidgetOptions."""
    return AddWidgetOptions(builder, widgetOptions)
def AddFileNameData(builder, fileNameData): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(fileNameData), 0)
def ImageViewOptionsAddFileNameData(builder, fileNameData):
    """This method is deprecated. Please switch to AddFileNameData."""
    return AddFileNameData(builder, fileNameData)
def AddCapInsets(builder, capInsets): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(capInsets), 0)
def ImageViewOptionsAddCapInsets(builder, capInsets):
    """This method is deprecated. Please switch to AddCapInsets."""
    return AddCapInsets(builder, capInsets)
def AddScale9Size(builder, scale9Size): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(scale9Size), 0)
def ImageViewOptionsAddScale9Size(builder, scale9Size):
    """This method is deprecated. Please switch to AddScale9Size."""
    return AddScale9Size(builder, scale9Size)
def AddScale9Enabled(builder, scale9Enabled): builder.PrependBoolSlot(4, scale9Enabled, 0)
def ImageViewOptionsAddScale9Enabled(builder, scale9Enabled):
    """This method is deprecated. Please switch to AddScale9Enabled."""
    return AddScale9Enabled(builder, scale9Enabled)
def End(builder): return builder.EndObject()
def ImageViewOptionsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)