# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LanguageSet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LanguageSet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLanguageSet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LanguageSet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LanguageSet
    def LanguageItems(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from flatbuffers.LanguageItem import LanguageItem
            obj = LanguageItem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LanguageSet
    def LanguageItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LanguageSet
    def LanguageItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def LanguageSetStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddLanguageItems(builder, languageItems): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(languageItems), 0)
def LanguageSetAddLanguageItems(builder, languageItems):
    """This method is deprecated. Please switch to AddLanguageItems."""
    return AddLanguageItems(builder, languageItems)
def StartLanguageItemsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def LanguageSetStartLanguageItemsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartLanguageItemsVector(builder, numElems)
def End(builder): return builder.EndObject()
def LanguageSetEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)