# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NodeTree(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NodeTree()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNodeTree(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # NodeTree
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NodeTree
    def Classname(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NodeTree
    def Children(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from flatbuffers.NodeTree import NodeTree
            obj = NodeTree()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NodeTree
    def ChildrenLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NodeTree
    def ChildrenIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # NodeTree
    def Options(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.Options import Options
            obj = Options()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NodeTree
    def CustomClassName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(4)
def NodeTreeStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddClassname(builder, classname): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(classname), 0)
def NodeTreeAddClassname(builder, classname):
    """This method is deprecated. Please switch to AddClassname."""
    return AddClassname(builder, classname)
def AddChildren(builder, children): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(children), 0)
def NodeTreeAddChildren(builder, children):
    """This method is deprecated. Please switch to AddChildren."""
    return AddChildren(builder, children)
def StartChildrenVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def NodeTreeStartChildrenVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartChildrenVector(builder, numElems)
def AddOptions(builder, options): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(options), 0)
def NodeTreeAddOptions(builder, options):
    """This method is deprecated. Please switch to AddOptions."""
    return AddOptions(builder, options)
def AddCustomClassName(builder, customClassName): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(customClassName), 0)
def NodeTreeAddCustomClassName(builder, customClassName):
    """This method is deprecated. Please switch to AddCustomClassName."""
    return AddCustomClassName(builder, customClassName)
def End(builder): return builder.EndObject()
def NodeTreeEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)