# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NodeAction(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NodeAction()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNodeAction(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # NodeAction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NodeAction
    def Duration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # NodeAction
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # NodeAction
    def TimeLines(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from flatbuffers.TimeLine import TimeLine
            obj = TimeLine()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NodeAction
    def TimeLinesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NodeAction
    def TimeLinesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # NodeAction
    def CurrentAnimationName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(4)
def NodeActionStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddDuration(builder, duration): builder.PrependInt32Slot(0, duration, 0)
def NodeActionAddDuration(builder, duration):
    """This method is deprecated. Please switch to AddDuration."""
    return AddDuration(builder, duration)
def AddSpeed(builder, speed): builder.PrependFloat32Slot(1, speed, 0.0)
def NodeActionAddSpeed(builder, speed):
    """This method is deprecated. Please switch to AddSpeed."""
    return AddSpeed(builder, speed)
def AddTimeLines(builder, timeLines): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(timeLines), 0)
def NodeActionAddTimeLines(builder, timeLines):
    """This method is deprecated. Please switch to AddTimeLines."""
    return AddTimeLines(builder, timeLines)
def StartTimeLinesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def NodeActionStartTimeLinesVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartTimeLinesVector(builder, numElems)
def AddCurrentAnimationName(builder, currentAnimationName): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(currentAnimationName), 0)
def NodeActionAddCurrentAnimationName(builder, currentAnimationName):
    """This method is deprecated. Please switch to AddCurrentAnimationName."""
    return AddCurrentAnimationName(builder, currentAnimationName)
def End(builder): return builder.EndObject()
def NodeActionEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)