# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PanelOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PanelOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPanelOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PanelOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PanelOptions
    def WidgetOptions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.WidgetOptions import WidgetOptions
            obj = WidgetOptions()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PanelOptions
    def BackGroundImageData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PanelOptions
    def ClipEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # PanelOptions
    def BgColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PanelOptions
    def BgStartColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PanelOptions
    def BgEndColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PanelOptions
    def ColorType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PanelOptions
    def BgColorOpacity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 255

    # PanelOptions
    def ColorVector(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.ColorVector import ColorVector
            obj = ColorVector()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PanelOptions
    def CapInsets(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.CapInsets import CapInsets
            obj = CapInsets()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PanelOptions
    def Scale9Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.FlatSize import FlatSize
            obj = FlatSize()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PanelOptions
    def BackGroundScale9Enabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def Start(builder): builder.StartObject(12)
def PanelOptionsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddWidgetOptions(builder, widgetOptions): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(widgetOptions), 0)
def PanelOptionsAddWidgetOptions(builder, widgetOptions):
    """This method is deprecated. Please switch to AddWidgetOptions."""
    return AddWidgetOptions(builder, widgetOptions)
def AddBackGroundImageData(builder, backGroundImageData): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(backGroundImageData), 0)
def PanelOptionsAddBackGroundImageData(builder, backGroundImageData):
    """This method is deprecated. Please switch to AddBackGroundImageData."""
    return AddBackGroundImageData(builder, backGroundImageData)
def AddClipEnabled(builder, clipEnabled): builder.PrependBoolSlot(2, clipEnabled, 0)
def PanelOptionsAddClipEnabled(builder, clipEnabled):
    """This method is deprecated. Please switch to AddClipEnabled."""
    return AddClipEnabled(builder, clipEnabled)
def AddBgColor(builder, bgColor): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(bgColor), 0)
def PanelOptionsAddBgColor(builder, bgColor):
    """This method is deprecated. Please switch to AddBgColor."""
    return AddBgColor(builder, bgColor)
def AddBgStartColor(builder, bgStartColor): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(bgStartColor), 0)
def PanelOptionsAddBgStartColor(builder, bgStartColor):
    """This method is deprecated. Please switch to AddBgStartColor."""
    return AddBgStartColor(builder, bgStartColor)
def AddBgEndColor(builder, bgEndColor): builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(bgEndColor), 0)
def PanelOptionsAddBgEndColor(builder, bgEndColor):
    """This method is deprecated. Please switch to AddBgEndColor."""
    return AddBgEndColor(builder, bgEndColor)
def AddColorType(builder, colorType): builder.PrependInt32Slot(6, colorType, 0)
def PanelOptionsAddColorType(builder, colorType):
    """This method is deprecated. Please switch to AddColorType."""
    return AddColorType(builder, colorType)
def AddBgColorOpacity(builder, bgColorOpacity): builder.PrependUint8Slot(7, bgColorOpacity, 255)
def PanelOptionsAddBgColorOpacity(builder, bgColorOpacity):
    """This method is deprecated. Please switch to AddBgColorOpacity."""
    return AddBgColorOpacity(builder, bgColorOpacity)
def AddColorVector(builder, colorVector): builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(colorVector), 0)
def PanelOptionsAddColorVector(builder, colorVector):
    """This method is deprecated. Please switch to AddColorVector."""
    return AddColorVector(builder, colorVector)
def AddCapInsets(builder, capInsets): builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(capInsets), 0)
def PanelOptionsAddCapInsets(builder, capInsets):
    """This method is deprecated. Please switch to AddCapInsets."""
    return AddCapInsets(builder, capInsets)
def AddScale9Size(builder, scale9Size): builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(scale9Size), 0)
def PanelOptionsAddScale9Size(builder, scale9Size):
    """This method is deprecated. Please switch to AddScale9Size."""
    return AddScale9Size(builder, scale9Size)
def AddBackGroundScale9Enabled(builder, backGroundScale9Enabled): builder.PrependBoolSlot(11, backGroundScale9Enabled, 0)
def PanelOptionsAddBackGroundScale9Enabled(builder, backGroundScale9Enabled):
    """This method is deprecated. Please switch to AddBackGroundScale9Enabled."""
    return AddBackGroundScale9Enabled(builder, backGroundScale9Enabled)
def End(builder): return builder.EndObject()
def PanelOptionsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)