# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Particle3DOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Particle3DOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsParticle3DOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Particle3DOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Particle3DOptions
    def Node3DOption(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.Node3DOption import Node3DOption
            obj = Node3DOption()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Particle3DOptions
    def FileData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(2)
def Particle3DOptionsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddNode3DOption(builder, node3DOption): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(node3DOption), 0)
def Particle3DOptionsAddNode3DOption(builder, node3DOption):
    """This method is deprecated. Please switch to AddNode3DOption."""
    return AddNode3DOption(builder, node3DOption)
def AddFileData(builder, fileData): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(fileData), 0)
def Particle3DOptionsAddFileData(builder, fileData):
    """This method is deprecated. Please switch to AddFileData."""
    return AddFileData(builder, fileData)
def End(builder): return builder.EndObject()
def Particle3DOptionsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)