# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScrollViewOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScrollViewOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScrollViewOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScrollViewOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScrollViewOptions
    def WidgetOptions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.WidgetOptions import WidgetOptions
            obj = WidgetOptions()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def BackGroundImageData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def ClipEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ScrollViewOptions
    def BgColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def BgStartColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def BgEndColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def ColorType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ScrollViewOptions
    def BgColorOpacity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 255

    # ScrollViewOptions
    def ColorVector(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.ColorVector import ColorVector
            obj = ColorVector()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def CapInsets(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.CapInsets import CapInsets
            obj = CapInsets()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def Scale9Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.FlatSize import FlatSize
            obj = FlatSize()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def BackGroundScale9Enabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ScrollViewOptions
    def InnerSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = o + self._tab.Pos
            from flatbuffers.FlatSize import FlatSize
            obj = FlatSize()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScrollViewOptions
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ScrollViewOptions
    def BounceEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ScrollViewOptions
    def ScrollbarEnabeld(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # ScrollViewOptions
    def ScrollbarAutoHide(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # ScrollViewOptions
    def ScrollbarAutoHideTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.2

def Start(builder): builder.StartObject(18)
def ScrollViewOptionsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddWidgetOptions(builder, widgetOptions): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(widgetOptions), 0)
def ScrollViewOptionsAddWidgetOptions(builder, widgetOptions):
    """This method is deprecated. Please switch to AddWidgetOptions."""
    return AddWidgetOptions(builder, widgetOptions)
def AddBackGroundImageData(builder, backGroundImageData): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(backGroundImageData), 0)
def ScrollViewOptionsAddBackGroundImageData(builder, backGroundImageData):
    """This method is deprecated. Please switch to AddBackGroundImageData."""
    return AddBackGroundImageData(builder, backGroundImageData)
def AddClipEnabled(builder, clipEnabled): builder.PrependBoolSlot(2, clipEnabled, 0)
def ScrollViewOptionsAddClipEnabled(builder, clipEnabled):
    """This method is deprecated. Please switch to AddClipEnabled."""
    return AddClipEnabled(builder, clipEnabled)
def AddBgColor(builder, bgColor): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(bgColor), 0)
def ScrollViewOptionsAddBgColor(builder, bgColor):
    """This method is deprecated. Please switch to AddBgColor."""
    return AddBgColor(builder, bgColor)
def AddBgStartColor(builder, bgStartColor): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(bgStartColor), 0)
def ScrollViewOptionsAddBgStartColor(builder, bgStartColor):
    """This method is deprecated. Please switch to AddBgStartColor."""
    return AddBgStartColor(builder, bgStartColor)
def AddBgEndColor(builder, bgEndColor): builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(bgEndColor), 0)
def ScrollViewOptionsAddBgEndColor(builder, bgEndColor):
    """This method is deprecated. Please switch to AddBgEndColor."""
    return AddBgEndColor(builder, bgEndColor)
def AddColorType(builder, colorType): builder.PrependInt32Slot(6, colorType, 0)
def ScrollViewOptionsAddColorType(builder, colorType):
    """This method is deprecated. Please switch to AddColorType."""
    return AddColorType(builder, colorType)
def AddBgColorOpacity(builder, bgColorOpacity): builder.PrependUint8Slot(7, bgColorOpacity, 255)
def ScrollViewOptionsAddBgColorOpacity(builder, bgColorOpacity):
    """This method is deprecated. Please switch to AddBgColorOpacity."""
    return AddBgColorOpacity(builder, bgColorOpacity)
def AddColorVector(builder, colorVector): builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(colorVector), 0)
def ScrollViewOptionsAddColorVector(builder, colorVector):
    """This method is deprecated. Please switch to AddColorVector."""
    return AddColorVector(builder, colorVector)
def AddCapInsets(builder, capInsets): builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(capInsets), 0)
def ScrollViewOptionsAddCapInsets(builder, capInsets):
    """This method is deprecated. Please switch to AddCapInsets."""
    return AddCapInsets(builder, capInsets)
def AddScale9Size(builder, scale9Size): builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(scale9Size), 0)
def ScrollViewOptionsAddScale9Size(builder, scale9Size):
    """This method is deprecated. Please switch to AddScale9Size."""
    return AddScale9Size(builder, scale9Size)
def AddBackGroundScale9Enabled(builder, backGroundScale9Enabled): builder.PrependBoolSlot(11, backGroundScale9Enabled, 0)
def ScrollViewOptionsAddBackGroundScale9Enabled(builder, backGroundScale9Enabled):
    """This method is deprecated. Please switch to AddBackGroundScale9Enabled."""
    return AddBackGroundScale9Enabled(builder, backGroundScale9Enabled)
def AddInnerSize(builder, innerSize): builder.PrependStructSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(innerSize), 0)
def ScrollViewOptionsAddInnerSize(builder, innerSize):
    """This method is deprecated. Please switch to AddInnerSize."""
    return AddInnerSize(builder, innerSize)
def AddDirection(builder, direction): builder.PrependInt32Slot(13, direction, 0)
def ScrollViewOptionsAddDirection(builder, direction):
    """This method is deprecated. Please switch to AddDirection."""
    return AddDirection(builder, direction)
def AddBounceEnabled(builder, bounceEnabled): builder.PrependBoolSlot(14, bounceEnabled, 0)
def ScrollViewOptionsAddBounceEnabled(builder, bounceEnabled):
    """This method is deprecated. Please switch to AddBounceEnabled."""
    return AddBounceEnabled(builder, bounceEnabled)
def AddScrollbarEnabeld(builder, scrollbarEnabeld): builder.PrependBoolSlot(15, scrollbarEnabeld, 1)
def ScrollViewOptionsAddScrollbarEnabeld(builder, scrollbarEnabeld):
    """This method is deprecated. Please switch to AddScrollbarEnabeld."""
    return AddScrollbarEnabeld(builder, scrollbarEnabeld)
def AddScrollbarAutoHide(builder, scrollbarAutoHide): builder.PrependBoolSlot(16, scrollbarAutoHide, 1)
def ScrollViewOptionsAddScrollbarAutoHide(builder, scrollbarAutoHide):
    """This method is deprecated. Please switch to AddScrollbarAutoHide."""
    return AddScrollbarAutoHide(builder, scrollbarAutoHide)
def AddScrollbarAutoHideTime(builder, scrollbarAutoHideTime): builder.PrependFloat32Slot(17, scrollbarAutoHideTime, 0.2)
def ScrollViewOptionsAddScrollbarAutoHideTime(builder, scrollbarAutoHideTime):
    """This method is deprecated. Please switch to AddScrollbarAutoHideTime."""
    return AddScrollbarAutoHideTime(builder, scrollbarAutoHideTime)
def End(builder): return builder.EndObject()
def ScrollViewOptionsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)