# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SliderOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SliderOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSliderOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SliderOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SliderOptions
    def WidgetOptions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.WidgetOptions import WidgetOptions
            obj = WidgetOptions()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SliderOptions
    def BarFileNameData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SliderOptions
    def BallNormalData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SliderOptions
    def BallPressedData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SliderOptions
    def BallDisabledData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SliderOptions
    def ProgressBarData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flatbuffers.ResourceData import ResourceData
            obj = ResourceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SliderOptions
    def Percent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 50

    # SliderOptions
    def Displaystate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def Start(builder): builder.StartObject(8)
def SliderOptionsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddWidgetOptions(builder, widgetOptions): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(widgetOptions), 0)
def SliderOptionsAddWidgetOptions(builder, widgetOptions):
    """This method is deprecated. Please switch to AddWidgetOptions."""
    return AddWidgetOptions(builder, widgetOptions)
def AddBarFileNameData(builder, barFileNameData): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(barFileNameData), 0)
def SliderOptionsAddBarFileNameData(builder, barFileNameData):
    """This method is deprecated. Please switch to AddBarFileNameData."""
    return AddBarFileNameData(builder, barFileNameData)
def AddBallNormalData(builder, ballNormalData): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ballNormalData), 0)
def SliderOptionsAddBallNormalData(builder, ballNormalData):
    """This method is deprecated. Please switch to AddBallNormalData."""
    return AddBallNormalData(builder, ballNormalData)
def AddBallPressedData(builder, ballPressedData): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(ballPressedData), 0)
def SliderOptionsAddBallPressedData(builder, ballPressedData):
    """This method is deprecated. Please switch to AddBallPressedData."""
    return AddBallPressedData(builder, ballPressedData)
def AddBallDisabledData(builder, ballDisabledData): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(ballDisabledData), 0)
def SliderOptionsAddBallDisabledData(builder, ballDisabledData):
    """This method is deprecated. Please switch to AddBallDisabledData."""
    return AddBallDisabledData(builder, ballDisabledData)
def AddProgressBarData(builder, progressBarData): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(progressBarData), 0)
def SliderOptionsAddProgressBarData(builder, progressBarData):
    """This method is deprecated. Please switch to AddProgressBarData."""
    return AddProgressBarData(builder, progressBarData)
def AddPercent(builder, percent): builder.PrependInt32Slot(6, percent, 50)
def SliderOptionsAddPercent(builder, percent):
    """This method is deprecated. Please switch to AddPercent."""
    return AddPercent(builder, percent)
def AddDisplaystate(builder, displaystate): builder.PrependBoolSlot(7, displaystate, 1)
def SliderOptionsAddDisplaystate(builder, displaystate):
    """This method is deprecated. Please switch to AddDisplaystate."""
    return AddDisplaystate(builder, displaystate)
def End(builder): return builder.EndObject()
def SliderOptionsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)